name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '47 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale due to inactivity'
          stale-pr-message: 'This PR is stale due to inactivity'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 120
